musicLibrary/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('solos.urls', namespace='solos')),
]

solos/urls.py
from django.conf.urls import url
from solos.views import index, SoloDetailView

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'solos/(?P<pk>\d+)/$', SoloDetailView.as_view(), name="detail"),
]

solos/models.py
from django.db import models


# Create your models here.
class Solo(models.Model):
    track = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    instrument = models.CharField(max_length=50)
    album = models.CharField(max_length=200)
    start_time = models.CharField(max_length=20, blank=True, null=True)
    end_time = models.CharField(max_length=20, blank=True, null=True)

solos/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from .models import Solo


# Create your views here.
def index(request):
    context = {'solos': []}

    if request.GET.keys():
        solos_queryset = Solo.objects.all()

        if request.GET.get('instrument', None):
            solos_queryset = solos_queryset.filter(
                instrument=request.GET.get('instrument', None)
            )
        if request.GET.get('artist', None):
            solos_queryset = solos_queryset.filter(
                artist=request.GET.get('artist', None)
            )
        context['solos'] = solos_queryset

    return render_to_response('solos/index.html', context)


class SoloDetailView(DetailView):
    model = Solo
    template_name = "solos/detail.html"

solos/templates/solos/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
        {% include "solos/common/css.html" %}
    {% endblock %}
</head>
<body>
{% include "solos/common/navbar.html" %}
{% block content %}

{% endblock %}
{% block js %}
    {% include "solos/common/js.html" %}
{% endblock %}
</body>
</html>

solos/templates/solos/common/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

solos/templates/solos/common/js.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

solos/templates/solos/common/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

solos/templates/solos/detail.html
{% extends "solos/common/base.html" %}

{% block content %}
   <p id="jmad-artist">{{ solo.artist }}</p>
   <p id="jmad-track">{{ solo.track }}</p>
   <p id="jmad-album">{{ solo.album }}</p>
   <p id="jmad-start-time">{{ solo.start_time }}</p>
   <p id="jmad-end-time">{{ solo.end_time }}</p>
{% endblock %}

solos/templates/solos/index.html
{% extends "solos/common/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="row">
                    <form action="#">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="jmad-instrument">Instrument</label>
                                <input type="text" class="form-control" id="jmad-instrument" name="instrument"
                                       placeholder="i.e. trumpet">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <label for="jmad-artist">Artist</label>
                            <input type="text" class="form-control" id="jmad-artist" name="artist" placeholder="i.e. Davis">
                        </div>
                        <div class="col-sm-4">
                            <button type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            {% for solo in solos %}
                <div class="col-sm-4">
                    <div class="jmad-search-result">
                        <a href="{% url 'solos:detail' solo.pk %}">
                            {{ solo.track }}: {{ solo.artist }} on {{ solo.instrument }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}